-- =====================================================================
-- project_learning : Database Schema (สารบัญ)
--
-- แยกไฟล์ตามระบบงาน เหมือนแท็บชีทในไฟล์ สอบทดสอบปัตตานี.xlsx
-- แต่ละไฟล์ PHP ที่เชื่อมกับตารางเหล่านี้จะมีคอมเมนต์อ้างอิงกลับมาที่นี่
-- =====================================================================

-- ข้อมูลผู้ใช้งาน (User Management)      -> database/users.sql          [ใช้ร่วมทุกระบบ: login/, user/, repair_system/, borrow_system/]
-- ระบบแจ้งซ่อมอุปกรณ์ (Repair System)   -> database/repair_system.sql  [ใช้งานจริงแล้ว]
-- ระบบยืมคืนอุปกรณ์ (Borrow System)      -> database/borrow_system.sql  [ใช้งานจริงแล้ว]
-- ระบบจัดการกิจกรรมนักเรียน               -> database/activity_system.sql [ใช้งานจริงแล้ว]
-- ระบบจัดการห้องเรียน/ห้องสอบ             -> database/classroom_system.sql [ใช้งานจริงแล้ว] (ตาราง classroom อยู่ใน repair_system.sql)
-- ระบบลา/ขออนุญาตนักเรียน                 -> database/leave_system.sql [ใช้งานจริงแล้ว]
